version: '3'
services:
  frontoffice:
    build:
      context: ./
      dockerfile: ./Dockerfile.angular
      args:
        project: frontoffice
    ports:
      - 8000:80
    restart: on-failure
    volumes:
      - frontoffice_vol:/usr/src/frontoffice/
      - node_modules:/usr/src/frontoffice/node_modules/
    networks:
      - monorepo_net
  api:
    build:
      context: ./
      dockerfile: ./Dockerfile.nest
      args:
        project: api
    ports:
      - 8003:3333
    restart: on-failure
    volumes:
      - api_vol:/usr/src/api/
      - node_modules:/usr/src/api/node_modules/
    networks:
      - monorepo_net

volumes:
  frontoffice_vol:
  api_vol:
  node_modules:

networks:
  monorepo_net:
    driver: bridge